# Generated by Django 3.1 on 2020-11-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0004_auto_20201126_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
